
import { z } from "zod"

// --- MOVIMIENTOS (KARDEX) ---
export const movimientoSchema = z.object({
    id_movimiento: z.string().optional(), // UUID generated by DB
    fecha_hora: z.string().optional(),
    tipo_movimiento: z.enum(['COMPRA', 'VENTA', 'PRODUCCION', 'AJUSTE', 'RETORNO']),
    id_sku: z.string().min(1, "SKU es requerido"),
    cantidad: z.coerce.number().refine((val) => val !== 0, "Cantidad no puede ser 0"),
    id_almacen: z.string().default('PRINCIPAL'),
    moneda_origen: z.string().optional(),
    costo_unit_doc: z.coerce.number().optional(),
    tipo_cambio: z.coerce.number().optional(),
    comentarios: z.string().optional()
})

// --- ENTRADAS (COMPRAS) ---
export const entradaDetalleSchema = z.object({
    id_sku: z.string().min(1, "SKU es requerido"),
    cantidad: z.coerce.number().positive("Cantidad debe ser mayor a 0"),
    costo_unitario: z.coerce.number().min(0, "Costo no puede ser negativo"),
    descuento: z.coerce.number().min(0).optional().default(0),
    total_linea: z.coerce.number().optional() // Calculated
})

export const entradaCabeceraSchema = z.object({
    id_proveedor: z.string().optional(), // Optional for Adjustments
    tipo_entrada: z.enum(['COMPRA', 'AJUSTE_POSITIVO', 'DEVOLUCION_CLIENTE']),
    fecha_registro: z.date().optional(),
    nro_documento_fisico: z.string().optional(),
    moneda: z.enum(['PEN', 'USD']),
    tipo_cambio: z.coerce.number().positive("Tipo de cambio inválido"),
    comentarios: z.string().optional(),
    estado: z.enum(['INGRESADO', 'ANULADO']).default('INGRESADO'),
    detalles: z.array(entradaDetalleSchema).min(1, "Debe agregar al menos un item")
}).superRefine((data, ctx) => {
    if (data.tipo_entrada === 'COMPRA' && !data.id_proveedor) {
        ctx.addIssue({
            code: z.ZodIssueCode.custom,
            message: "Proveedor es requerido para Compras",
            path: ["id_proveedor"]
        })
    }
})

// --- SALIDAS (VENTAS/PRODUCCION) ---
export const salidaDetalleSchema = z.object({
    id_sku: z.string().min(1, "SKU es requerido"),
    cantidad: z.coerce.number().positive("Cantidad debe ser mayor a 0"),
    precio_unitario: z.coerce.number().min(0),
    subtotal: z.coerce.number().optional()
})

export const salidaCabeceraSchema = z.object({
    tipo_salida: z.enum(['VENTA', 'PRODUCCION', 'AJUSTE_NEGATIVO', 'DEVOLUCION_PROVEEDOR']),
    id_cliente: z.string().optional(), // Optional for Adjustments
    fecha: z.date().optional(),
    comentario: z.string().optional(),
    estado: z.enum(['CONFIRMADO', 'ANULADO']).default('CONFIRMADO'),
    detalles: z.array(salidaDetalleSchema).min(1, "Debe agregar al menos un item")
}).superRefine((data, ctx) => {
    if (data.tipo_salida === 'VENTA' && !data.id_cliente) {
        ctx.addIssue({
            code: z.ZodIssueCode.custom,
            message: "Cliente es requerido para Ventas",
            path: ["id_cliente"]
        })
    }
})

export type MovimientoForm = z.infer<typeof movimientoSchema>
export type EntradaForm = z.infer<typeof entradaCabeceraSchema>
export type EntradaDetalleForm = z.infer<typeof entradaDetalleSchema>
export type SalidaForm = z.infer<typeof salidaCabeceraSchema>
export type SalidaDetalleForm = z.infer<typeof salidaDetalleSchema>
